//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Exceptions.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF informado já existe no sistema.
        /// </summary>
        public static string CPF_EXISTE {
            get {
                return ResourceManager.GetString("CPF_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF entered is invalid..
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s CPF must be informed..
        /// </summary>
        public static string CPF_VAZIO {
            get {
                return ResourceManager.GetString("CPF_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered email already exists in the system.
        /// </summary>
        public static string EMAIL_EXISTE {
            get {
                return ResourceManager.GetString("EMAIL_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail entered is invalid..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be provided..
        /// </summary>
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is invalid..
        /// </summary>
        public static string NASCIMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("NASCIMENTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth must be informed.
        /// </summary>
        public static string NASCIMENTO_VAZIO {
            get {
                return ResourceManager.GetString("NASCIMENTO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password must be at least.
        /// </summary>
        public static string SENHA_INVALIDA_ESP {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA_ESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password must have at least 1 capital letter..
        /// </summary>
        public static string SENHA_INVALIDA_MAIUSCULO {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA_MAIUSCULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password must be between 6 to 10 letters long..
        /// </summary>
        public static string SENHA_INVALIDA_QTD {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA_QTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password must be provided..
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number..
        /// </summary>
        public static string TELEFONE_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be provided.
        /// </summary>
        public static string TELEFONE_VAZIO {
            get {
                return ResourceManager.GetString("TELEFONE_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists in our system..
        /// </summary>
        public static string USUARIO_EXISTE {
            get {
                return ResourceManager.GetString("USUARIO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name..
        /// </summary>
        public static string USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be provided..
        /// </summary>
        public static string USUARIO_VAZIO {
            get {
                return ResourceManager.GetString("USUARIO_VAZIO", resourceCulture);
            }
        }
    }
}
