//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Exceptions.Resources.ResourceErrorMessage", typeof(ResourceErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF informado já existe no sistema.
        /// </summary>
        public static string CPF_EXISTE {
            get {
                return ResourceManager.GetString("CPF_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF informado é invalido..
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF do usuario deve ser informado..
        /// </summary>
        public static string CPF_VAZIO {
            get {
                return ResourceManager.GetString("CPF_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail informado já existe no sistema.
        /// </summary>
        public static string EMAIL_EXISTE {
            get {
                return ResourceManager.GetString("EMAIL_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Informado é invalido..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail deve ser informado..
        /// </summary>
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha estão invalidos..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento é invalido..
        /// </summary>
        public static string NASCIMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("NASCIMENTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento deve ser informado.
        /// </summary>
        public static string NASCIMENTO_VAZIO {
            get {
                return ResourceManager.GetString("NASCIMENTO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto não encontrado..
        /// </summary>
        public static string OBJETO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("OBJETO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha atual está invalida..
        /// </summary>
        public static string SENHA_ATUAL_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_ATUAL_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não são iguais..
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de usuario deve ter pelo menos .
        /// </summary>
        public static string SENHA_INVALIDA_ESP {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA_ESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de usuario deve ter pelo menos 1 letra maiuscula..
        /// </summary>
        public static string SENHA_INVALIDA_MAIUSCULO {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA_MAIUSCULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de usuario deve ter entre 6 a 10 letras..
        /// </summary>
        public static string SENHA_INVALIDA_QTD {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA_QTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de usuario deve ser informado..
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de telefone é invalido..
        /// </summary>
        public static string TELEFONE_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de telefone deve ser informado.
        /// </summary>
        public static string TELEFONE_VAZIO {
            get {
                return ResourceManager.GetString("TELEFONE_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessão expirada, entre novamente..
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuario já existe em nosso sistema..
        /// </summary>
        public static string USUARIO_EXISTE {
            get {
                return ResourceManager.GetString("USUARIO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuario é invalido..
        /// </summary>
        public static string USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já está logado..
        /// </summary>
        public static string USUARIO_LOGADO {
            get {
                return ResourceManager.GetString("USUARIO_LOGADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem permissão para acessar este recurso..
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de Usuario deve ser informado..
        /// </summary>
        public static string USUARIO_VAZIO {
            get {
                return ResourceManager.GetString("USUARIO_VAZIO", resourceCulture);
            }
        }
    }
}
